title: "Remote Lab"
description: ""
url: ""
baseurl: "/documentation"
github_username: PhysicsRemotelab

# Build settings
theme: minima

port: 8080

include:
  - _pages

header_pages:
  - _pages/menu-dependencies.markdown
  - _pages/menu-local-development.markdown
  - _pages/menu-labs.markdown

exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
